### ISSUE TITLE
page cached for logged-in and not-logged-in users / mediawiki 1.39

### ISSUE THREAD

**Issue by marohh** [marohh/mediawikiRemoveRedlinks#11]
observed in mediawiki 1.39 with standard cache settings. 

Page content is cached between logged-in and not-logged-in users. 
This leads to the visualization of red links to be defined by whatever category renders the page first. 

Cache disabling may be required if both user categories access the wiki.

**Comment by thecutefinder** [comment]
I'm currently investigating this w/ help from some people in the MediaWiki IRC and Discord:
![image](https://user-images.githubusercontent.com/123335166/223225405-ee4e82bb-4709-41ff-8b40-e24b4d95b2d6.png)

**Comment by maromagimoro** [comment]
is it getting fixed? and does it happens on 1.40 too?

**Comment by RhinosF1** [comment]
https://github.com/wikimedia/mediawiki-extensions-WikiTextLoggedInOut/blob/master/includes/WikiTextLoggedInOut.php#L51 should show how to register a parser option

**Comment by colleirose** [comment]
https://github.com/marohh/mediawikiRemoveRedlinks/commit/20755d4b07496f5f437b75bdb58edf90e60cec41 fixed this and https://github.com/marohh/mediawikiRemoveRedlinks/commit/08dce0000a21cbbd05aff9961da56d174e3a02a9 broke it again

**Comment by colleirose** [comment]
Just revert back to 20755d4b07496f5f437b75bdb58edf90e60cec41 and change it so that if the config is set to always hide redlinks, don't add the data-redlinks attribute
